# Generated by Django 5.2.8 on 2025-11-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('ProductName', models.TextField()),
                ('Price', models.FloatField()),
                ('ProductType', models.TextField()),
                ('SupplierName', models.TextField()),
                ('Ratings', models.FloatField()),
            ],
        ),
    ]
